### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by zxfzqf** [xiongyihui/python-webrtc-audio-processing#1]

**Comment by zxfzqf** [comment]
OS:centos 7 64
python: 3.6
Installation method : pip install
run code : `from webrtc_audio_processing import AudioProcessingModule as AP`
error info : `raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/*****/anaconda3/envs/py36/lib/python3.6/site-packages/webrtc_audio_processing/__init__.py", line 2, in <module>
    from .webrtc_audio_processing import AudioProcessingModule
ModuleNotFoundError: No module named 'webrtc_audio_processing.webrtc_audio_processing'`

How can I modify it to use it ?
thx!

**Comment by xiongyihui** [comment]
Thanks for the report. It's a bug. Just fixed it.
You can try the latest version: `pip install -U webrtc-audio-processing`
