### ISSUE TITLE
hope for echo cancellation

### ISSUE THREAD

**Issue by zyb8543d** [xiongyihui/python-webrtc-audio-processing#5]
I try to modify the echo cancellation script follows your aec script.
it failed and out empty audio.

**Comment by xiongyihui** [comment]
You should try the latest AEC3 of webrtc, not this one

**Comment by qmpzzpmq** [comment]
Could you give a example or url of it ?

**Comment by sjkoelle** [comment]
@v-yunbin did you ever figure out a solution?
