### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by WestbrookZero** [xiongyihui/python-webrtc-audio-processing#9]
git submodule init && git submodule update
python-webrtc-audio-processing>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    ap_sources.remove('webrtc-audio-processing/webrtc/system_wrappers/source/rw_lock_generic.cc')
ValueError: list.remove(x): x not in list

**Comment by kli017** [comment]
hello I got the same error. did you solved?
